// <auto-generated />
namespace GeneralShop.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class themdulieuuser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(themdulieuuser));
        
        string IMigrationMetadata.Id
        {
            get { return "201804050705032_them-du-lieu-user"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
